plugins {
    id 'java'
}

allprojects {
    group = 'dev.hearthsmp'
    version = '0.1.0-SNAPSHOT'

    repositories {
        mavenCentral()
        maven { url = 'https://repo.papermc.io/repository/maven-public/' }
        maven { url = 'https://repo.extendedclip.com/content/repositories/placeholderapi/' }
    }
}

subprojects {
    apply plugin: 'java'

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(21)
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }
}
