rootProject.name = 'Hearth-plugins'

include 'HearthCore'
include 'HearthAuth'
include 'HearthClaims'
include 'HearthEconomy'
include 'HearthHomes'
include 'HearthMarket'
include 'HearthQuests'
include 'HearthAchievements'
include 'HearthStats'
include 'HearthSeasons'
include 'HearthLore'
include 'HearthEvents'
include 'HearthRewards'
include 'HearthChat'
include 'HearthCosmetics'
include 'HearthDiscord'
include 'HearthWorld'
